### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by ckbharti** [Goutham88/R-Peak-Detector-using-CNN-s#3]
![error](https://user-images.githubusercontent.com/46262437/59157353-f92acc00-8ac6-11e9-8dad-81a5d5a9bf61.PNG)
![error](https://user-images.githubusercontent.com/46262437/59157355-06e05180-8ac7-11e9-93ae-bba56371579c.PNG)

**Comment by Goutham88** [comment]
Hi @ckbharti, Thanks for trying this out and raising the issue.
Can you please show us the temp.py file? 
Also, Please make that the .mat files are present in the working directory.
We are currently loading it using scipy library

**Comment by ckbharti** [comment]
Hi, Goutham88 , i just copy and pasted your code to run. .mat file is in working directory. i also installed scipy library. could you explain 'signal' in ecg=a('signal').

**Comment by Goutham88** [comment]
![image](https://user-images.githubusercontent.com/13810239/59654666-e003d880-91b4-11e9-8d8a-00a1c7db98ec.png)
Can you please try the above commands in the folder where the 101.mat is present and share the output?

**Comment by ckbharti** [comment]
![github error](https://user-images.githubusercontent.com/46262437/59767763-a15b4480-92c0-11e9-857c-80de0cbf9b67.PNG)

**Comment by ckbharti** [comment]
Is annotation file is required in current directory. if yes then in which format?

**Comment by Goutham88** [comment]
@ckbharti Sorry, I'm not able to see the code which you have written because of the window. Can you please move it and share the screenshot again?

And for the other question, Can you try it placing in the current directory?

Can you just copy, paste and run the following after u place it the current folder?
import scipy.io
a=scipy.io.loadmat('101.mat')
print(a)

**Comment by Goutham88** [comment]
@ckbharti 
Can you please share the screenshot?
